---
- name: OpenStack | create glance user
  openstack.cloud.identity_user:
    cloud: pbos
    name: glance
    password: "{{ glance_password }}"
    domain: default
    default_project: service
    state: present
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true
  no_log: true

- name: OpenStack | add glance user to admin role
  openstack.cloud.role_assignment:
    cloud: pbos
    user: glance
    role: admin
    project: service
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true

- name: OpenStack | create image service for glance
  openstack.cloud.catalog_service:
    cloud: pbos
    name: glance
    service_type: image
    description: OpenStack Image Service
    state: present
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true

- name: OpenStack | create endpoint for glance
  openstack.cloud.endpoint:
    cloud: pbos
    service: glance
    endpoint_interface: "{{ item }}"
    url: "http://{{ keepalived_vip }}:9292"
    region: RegionOne
    state: present
  loop:
    - public
    - internal
    - admin
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true
...
