---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ os_service_init }}"
  become: true

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "0640"
    backup: true
  loop: "{{ os_service_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart service

- name: Setup | create oslo concurrency lock directory
  ansible.builtin.file:
    path: "/var/lock/glance"
    state: directory
    mode: "0755"
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
  become: true

- name: Setup | create db tables
  ansible.builtin.shell: su -s /bin/sh -c "glance-manage db_sync" glance
  become: true
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true

- name: Setup | include ceph glance keyring task
  ansible.builtin.include_tasks: ceph_glance_keyring.yml
  when: '"ceph" in storage_backends'
...
