---
- name: Setup | copy glance init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_distribution | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - {dest: "/etc/init.d/glance-api"}
  become: true

- name: Setup | template glance-api.conf
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_distribution | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "glance"
    mode: "0640"
    backup: true
  loop:
    - {dest: "/etc/glance/glance-api.conf"}
    - {dest: "/etc/glance/glance-api-uwsgi-bind.ini"}
  become: true
  notify:
    - systemctl restart glance-api service

- name: Setup | create glance db tables
  ansible.builtin.shell: su -s /bin/bash glance -c "glance-manage db_sync"
  become: true
...
