---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_distribution | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - {dest: "/etc/init.d/glance-api"}
  become: true

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_distribution | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "0640"
    backup: true
  loop:
    - {dest: "/etc/glance/glance-api.conf"}
    - {dest: "/etc/glance/glance-api-uwsgi-bind.ini"}
  become: true
  notify:
    - systemctl restart service

- name: Setup | create db tables
  ansible.builtin.shell: su -s /bin/sh -c "glance-manage db_sync" glance
  become: true
  delegate_to: "{{ groups['glance'][0] }}"
  run_once: true
...
